name: Non-Flesh Tokens
author: Matt Bierner
description: "Collection of 308 NFTs, each representing a unique block of two high resolution, full-body portraits"
url: https://nonfleshtokens.com

publicUrl: https://nonfleshtokens.com

kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false

permalink: /:title/

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - support
  - src
  - node_modules

